//! Starting a dev container: the script a visible Command terminal runs.
//!
//! The server decides everything up front from the approved plan (reuse, create,
//! rebuild, which lifecycle hooks run) and writes a bash script of plain docker
//! commands, each echoed before it runs and bounded by `timeout`. Values that may be
//! secret (`${localEnv:…}` expansions) reach docker through the script's environment
//! or an env file (0600, deleted after use), never through argv. The script's output
//! is the build/up log the user watches.
//!
//! Engines:
//! * **docker** (built in): `docker build` / `docker pull`, `docker run -d` with the
//!   workspace bind mount, mounts, filtered `runArgs`, `containerEnv`, ports published
//!   on 127.0.0.1, `--init`, the keep-alive command, VS Code's labels; or `docker
//!   compose up -d` with an override file carrying the labels; then the lifecycle hooks.
//! * **cli**: `devcontainer up`, whose JSON result names the container, remote user
//!   and workspace folder. It handles features, compose and lifecycle hooks itself.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::json;

use super::config::{Cmd, DevConfig, Lifecycle, Source};
use super::docker::ContainerInfo;
use super::exec::WRAPPER;
use super::plan::Engine;
use super::{sh_quote, sh_quote_always};

/// Timeouts (seconds).
const T_BUILD: u64 = 3600;
const T_RUN: u64 = 600;
const T_HOOK: u64 = 3600;
const T_SHORT: u64 = 120;

/// Where Workbench's lifecycle marker lives in containers it created.
pub const MARKER: &str = "/var/lib/workbench-devcontainer/created";

pub struct UpInput<'a> {
    pub project_id: &'a str,
    pub root: &'a Path,
    pub config_abs: &'a Path,
    /// Execution values (`${localEnv:…}` resolved).
    pub cfg: &'a DevConfig,
    /// Display values (for the echoed commands).
    pub shown: &'a DevConfig,
    pub hash: &'a str,
    pub engine: Engine,
    pub docker: &'a str,
    /// The devcontainer CLI command (argv prefix).
    pub cli: Option<Vec<String>>,
    pub existing: Option<&'a ContainerInfo>,
    pub rebuild: bool,
    /// A reused container Workbench made: run the create hooks when its marker is
    /// missing (an earlier start failed before they finished).
    pub check_marker: bool,
    pub work: &'a Path,
    pub host_uid: u32,
    pub host_gid: u32,
    pub cols: u16,
    pub rows: u16,
    pub container_name: String,
    pub compose_project: String,
    pub image_tag: String,
    /// Host ports to publish: `(container port, host port or 0 for any free one)`.
    pub publish: Vec<(u16, u16)>,
}

pub struct UpScript {
    pub script: String,
    pub env: Vec<(String, Option<String>)>,
    /// `devcontainer up`'s JSON result (CLI engine).
    pub result_file: Option<PathBuf>,
    /// Files to delete once the script finished (it deletes them itself too).
    pub temp_files: Vec<PathBuf>,
    /// Values to mask in the output.
    pub secrets: Vec<String>,
}

const HEADER: &str = r#"#!/usr/bin/env bash
# Generated by Workbench from an approved dev container plan.
set -uo pipefail
C_STEP=$'\e[1;36m'; C_DIM=$'\e[2m'; C_ERR=$'\e[1;31m'; C_OK=$'\e[1;32m'; C_RST=$'\e[0m'
step() { printf '\n%s▶ %s%s\n' "$C_STEP" "$1" "$C_RST"; }
show() { printf '%s$ %s%s\n' "$C_DIM" "$1" "$C_RST"; }
fail() { printf '\n%s✖ %s%s\n' "$C_ERR" "$1" "$C_RST"; exit 1; }
run() { local t=$1; shift; timeout --foreground -k 10 "$t" "$@"; }
"#;

struct Script {
    s: String,
}

impl Script {
    fn line(&mut self, l: &str) {
        self.s.push_str(l);
        self.s.push('\n');
    }
    fn step(&mut self, title: &str) {
        self.line(&format!("step {}", sh_quote_always(title)));
    }
    fn show(&mut self, text: &str) {
        self.line(&format!("show {}", sh_quote_always(text)));
    }
    /// Echo `shown`, run `argv` with a timeout, fail with `what` on error.
    fn run(&mut self, shown: &str, argv: &[String], timeout: u64, what: &str) {
        self.show(shown);
        let cmd: Vec<String> = argv.iter().map(|a| sh_quote(a)).collect();
        self.line(&format!("run {timeout} {} || fail {}", cmd.join(" "), sh_quote_always(what)));
    }
}

fn q(v: &[String]) -> String {
    v.iter().map(|a| sh_quote(a)).collect::<Vec<_>>().join(" ")
}

/// `runArgs` Workbench passes on: flags that would break how it manages the container
/// (`--rm`, detach/attach/tty flags, `--cidfile`) are dropped, and `-e K=V` moves to
/// the env file (values stay out of argv). Returns (args, moved env, own --name?).
pub fn filter_run_args(args: &[String]) -> (Vec<String>, Vec<(String, String)>, Option<String>) {
    let mut out = vec![];
    let mut env = vec![];
    let mut name = None;
    let mut i = 0;
    while i < args.len() {
        let a = args[i].as_str();
        let (flag, inline) = match a.split_once('=') {
            Some((f, v)) if f.starts_with("--") => (f, Some(v.to_string())),
            _ => (a, None),
        };
        let mut value = || {
            inline.clone().or_else(|| {
                i += 1;
                args.get(i).cloned()
            })
        };
        match flag {
            "--rm" | "-d" | "--detach" | "-i" | "--interactive" | "-t" | "--tty" | "-it" | "-ti" => {}
            "--cidfile" | "-a" | "--attach" => {
                value();
            }
            "--name" => name = value(),
            "-e" | "--env" => {
                if let Some(v) = value() {
                    match v.split_once('=') {
                        Some((k, val)) if super::config::valid_env_name(k) && !val.contains('\n') => env.push((k.to_string(), val.to_string())),
                        _ => out.extend(["-e".to_string(), v]),
                    }
                }
            }
            _ => out.push(args[i].clone()),
        }
        i += 1;
    }
    (out, env, name)
}

/// The keep-alive entrypoint of `overrideCommand` (as the devcontainer CLI's).
const KEEP_ALIVE: &str = "echo Container started\ntrap \"exit 0\" 15\nwhile sleep 1 & wait $!; do :; done";

/// The updateRemoteUserUID image layer (same effect as the devcontainer CLI's).
pub const UID_DOCKERFILE: &str = r#"ARG BASE_IMAGE
FROM $BASE_IMAGE
USER root
ARG REMOTE_USER
ARG NEW_UID
ARG NEW_GID
SHELL ["/bin/sh", "-c"]
RUN eval $(sed -n "s/${REMOTE_USER}:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDER=\3/p" /etc/passwd); \
	eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_UID}:.*/EXISTING_USER=\1/p" /etc/passwd); \
	eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_GID}:.*/EXISTING_GROUP=\1/p" /etc/group); \
	if [ -z "$OLD_UID" ]; then \
		echo "Remote user not found in /etc/passwd ($REMOTE_USER)."; \
	elif [ "$OLD_UID" = "$NEW_UID" -a "$OLD_GID" = "$NEW_GID" ]; then \
		echo "UIDs and GIDs are the same ($NEW_UID:$NEW_GID)."; \
	elif [ "$OLD_UID" != "$NEW_UID" -a -n "$EXISTING_USER" ]; then \
		echo "User with UID exists ($EXISTING_USER=$NEW_UID)."; \
	else \
		if [ "$OLD_GID" != "$NEW_GID" -a -n "$EXISTING_GROUP" ]; then \
			echo "Group with GID exists ($EXISTING_GROUP=$NEW_GID)."; \
			NEW_GID="$OLD_GID"; \
		fi; \
		echo "Updating UID:GID from $OLD_UID:$OLD_GID to $NEW_UID:$NEW_GID."; \
		sed -i -e "s/\(${REMOTE_USER}:[^:]*:\)[^:]*:[^:]*/\1${NEW_UID}:${NEW_GID}/" /etc/passwd; \
		if [ "$OLD_GID" != "$NEW_GID" ]; then \
			sed -i -e "s/\([^:]*:[^:]*:\)${OLD_GID}:/\1${NEW_GID}:/" /etc/group; \
		fi; \
		chown -R $NEW_UID:$NEW_GID $HOME_FOLDER; \
	fi;
ARG IMAGE_USER
USER $IMAGE_USER
"#;

/// `devcontainer.metadata` for a container Workbench creates, when the config names a
/// user (VS Code and the CLI read the remote user from it).
fn metadata_label(c: &DevConfig) -> Option<String> {
    if c.remote_user.is_none() && c.container_user.is_none() {
        return None;
    }
    let mut o = serde_json::Map::new();
    if let Some(u) = &c.remote_user {
        o.insert("remoteUser".into(), json!(u));
    }
    if let Some(u) = &c.container_user {
        o.insert("containerUser".into(), json!(u));
    }
    Some(json!([o]).to_string())
}

/// The user lifecycle hooks run as.
pub fn hook_user(c: &DevConfig) -> Option<String> {
    c.remote_user.clone().or_else(|| c.container_user.clone())
}

/// Lines running one hook (parallel commands in the background, all awaited).
fn hook_lines(s: &mut Script, key: &str, l: &Lifecycle, shown: Option<&Lifecycle>) {
    s.step(key);
    let render = |cmd: &Cmd| -> String {
        match cmd {
            Cmd::Shell(text) => format!("/bin/sh -c {}", sh_quote_always(text)),
            Cmd::Exec(argv) => q(argv),
        }
    };
    let shown_text = |i: usize, cmd: &Cmd| shown.and_then(|l| l.commands.get(i)).map(|(_, c)| c.text()).unwrap_or_else(|| cmd.text());
    if l.commands.len() == 1 {
        let (_, cmd) = &l.commands[0];
        s.line(&format!("lc {} {} || fail {}", sh_quote_always(&shown_text(0, cmd)), render(cmd), sh_quote_always(&format!("{key} failed"))));
        return;
    }
    s.line("pids=()");
    for (i, (label, cmd)) in l.commands.iter().enumerate() {
        let name = label.clone().unwrap_or_else(|| format!("#{i}"));
        s.line(&format!("lc {} {} & pids+=($!)", sh_quote_always(&format!("[{name}] {}", shown_text(i, cmd))), render(cmd)));
    }
    s.line("rc=0; for p in \"${pids[@]}\"; do wait \"$p\" || rc=1; done");
    s.line(&format!("[ $rc -eq 0 ] || fail {}", sh_quote_always(&format!("{key} failed"))));
}

/// Host-side `initializeCommand` (in the project folder).
fn initialize_lines(s: &mut Script, l: &Lifecycle, shown: Option<&Lifecycle>) {
    s.step("initializeCommand (on this computer)");
    for (i, (_, cmd)) in l.commands.iter().enumerate() {
        let text = shown.and_then(|l| l.commands.get(i)).map(|(_, c)| c.text()).unwrap_or_else(|| cmd.text());
        s.show(&text);
        let run = match cmd {
            Cmd::Shell(t) => format!("/bin/sh -c {}", sh_quote_always(t)),
            Cmd::Exec(argv) => q(argv),
        };
        s.line(&format!("run {T_HOOK} {run} || fail 'initializeCommand failed'"));
    }
}

fn env_file_line(k: &str, v: &str) -> Option<String> {
    (!v.contains('\n') && !v.contains('\r')).then(|| format!("{k}={v}\n"))
}

/// Build the script for `i`. Writes the env/override files it needs into `i.work`.
pub fn script(i: &UpInput) -> anyhow::Result<UpScript> {
    let mut s = Script { s: HEADER.to_string() };
    let mut env: Vec<(String, Option<String>)> = vec![];
    let mut temp: Vec<PathBuf> = vec![];
    let mut secrets: Vec<String> = vec![];
    let c = i.cfg;
    let root = i.root.display().to_string();
    let config_file = i.config_abs.display().to_string();
    s.line(&format!("DOCKER={}", sh_quote(i.docker)));
    s.line(&format!("WRAPPER={}", sh_quote_always(WRAPPER)));
    s.line(&format!("cd {} || fail 'the project folder is gone'", sh_quote(&root)));
    s.line("CID=''");
    // Values the display config does not show (host env) are masked in the output, by the
    // terminal's redactor and with its floor: values under 8 characters are not masked
    // anywhere in Workbench (they would blank ordinary output, and reveal themselves by it).
    for (k, v) in &c.container_env {
        if i.shown.container_env.get(k) != Some(v) {
            secrets.push(v.clone());
        }
    }
    for (k, v) in &c.remote_env {
        if let Some(v) = v {
            if i.shown.remote_env.get(k).and_then(|x| x.as_ref()) != Some(v) {
                secrets.push(v.clone());
            }
        }
    }

    // Lifecycle exec arguments: user, folder, remoteEnv as templates.
    let user = hook_user(c);
    let mut exec_args: Vec<String> = vec![];
    let mut tpl_names = vec![];
    let mut unset = vec![];
    for (k, v) in &c.remote_env {
        match v {
            Some(v) => {
                env.push((format!("WB_T_{k}"), Some(super::exec::template(v))));
                exec_args.extend(["-e".into(), format!("WB_T_{k}")]);
                tpl_names.push(k.clone());
            }
            None => unset.push(k.clone()),
        }
    }
    if !tpl_names.is_empty() {
        env.push(("WB_TPL_NAMES".into(), Some(tpl_names.join(" "))));
        exec_args.extend(["-e".into(), "WB_TPL_NAMES".into()]);
    }
    if !unset.is_empty() {
        env.push(("WB_UNSET_NAMES".into(), Some(unset.join(" "))));
        exec_args.extend(["-e".into(), "WB_UNSET_NAMES".into()]);
    }

    if i.engine == Engine::Cli {
        let cli = i.cli.clone().ok_or_else(|| anyhow::anyhow!("the devcontainer CLI is not available"))?;
        let result = i.work.join("up-result.json");
        let mut argv = cli.clone();
        argv.extend([
            "up".into(),
            "--workspace-folder".into(),
            root.clone(),
            "--config".into(),
            config_file.clone(),
            "--docker-path".into(),
            i.docker.to_string(),
            "--terminal-columns".into(),
            i.cols.to_string(),
            "--terminal-rows".into(),
            i.rows.to_string(),
        ]);
        if i.rebuild {
            argv.push("--remove-existing-container".into());
        }
        s.step("devcontainer up");
        s.show(&q(&argv));
        s.line(&format!("run {T_BUILD} {} > {}", q(&argv), sh_quote(&result.display().to_string())));
        s.line("rc=$?");
        s.line(&format!("tail -n 1 {} | cut -c1-2000", sh_quote(&result.display().to_string())));
        s.line("[ $rc -eq 0 ] || fail \"devcontainer up failed (exit $rc)\"");
        s.line(&format!("printf '\\n%s✔ Dev container is ready%s\\n' \"$C_OK\" \"$C_RST\""));
        return Ok(UpScript { script: s.s, env, result_file: Some(result), temp_files: temp, secrets });
    }

    // Lifecycle helper for the built-in engine. Without a user in the config, hooks run
    // as the remote user the image's `devcontainer.metadata` names (as the CLI does).
    s.line(&format!("EXEC_ARGS=({})", q(&exec_args)));
    s.line(&format!("HOOK_USER={}", sh_quote_always(user.as_deref().unwrap_or(""))));
    s.line(r#"meta_user() { "$DOCKER" "$@" --format '{{index .Config.Labels "devcontainer.metadata"}}' 2>/dev/null | grep -o '"\(remoteUser\|containerUser\)": *"[^"]*"' | tail -n 1 | sed 's/.*"\([^"]*\)"$/\1/'; }"#);
    s.line(&format!(
        "lc() {{ show \"$1\"; shift; [ -n \"$HOOK_USER\" ] || HOOK_USER=$(meta_user inspect \"$CID\"); run {T_HOOK} \"$DOCKER\" exec -t --detach-keys=ctrl-^,ctrl-^,ctrl-^ -w {} ${{HOOK_USER:+-u \"$HOOK_USER\"}} \"${{EXEC_ARGS[@]}}\" \"$CID\" /bin/sh -c \"$WRAPPER\" wb-exec \"$@\"; }}",
        sh_quote(&c.workspace_folder)
    ));

    if let Some(l) = &c.initialize_command {
        initialize_lines(&mut s, l, i.shown.initialize_command.as_ref());
    }

    // Existing container: rebuild removes it; otherwise it is started (or already runs).
    // Compose always runs `up` (it starts every service and keeps unchanged ones).
    let mut fresh = true;
    s.line("FRESH=1; STARTED=1");
    if let Some(e) = i.existing {
        if i.rebuild {
            s.step("Removing the old container");
            if let Source::Compose { .. } = c.source {
                let mut argv = vec![i.docker.to_string(), "compose".into(), "-p".into(), i.compose_project.clone()];
                argv.extend(["down".into()]);
                s.run(&q(&argv), &argv, T_SHORT, "could not remove the old containers");
            } else {
                let argv = vec![i.docker.to_string(), "rm".into(), "-f".into(), e.id.clone()];
                s.run(&q(&argv), &argv, T_SHORT, "could not remove the old container");
            }
        } else if !c.is_compose() {
            fresh = false;
            s.line(&format!("CID={}; FRESH=0; STARTED={}", sh_quote(&e.id), if e.running { 0 } else { 1 }));
            if !e.running {
                s.step("Starting the container");
                let argv = vec![i.docker.to_string(), "start".into(), e.id.clone()];
                s.run(&q(&argv), &argv, T_RUN, "could not start the container");
            } else {
                s.line(&format!("printf 'Container %s is running.\\n' {}", sh_quote(&e.name)));
            }
        }
    }

    // The env file for containerEnv (and `-e K=V` runArgs).
    let (run_args, run_env, own_name) = filter_run_args(&c.run_args);
    let env_file = i.work.join("container.env");
    let mut env_text = String::new();
    for (k, v) in c.container_env.iter().map(|(k, v)| (k.clone(), v.clone())).chain(run_env) {
        match env_file_line(&k, &v) {
            Some(l) => env_text.push_str(&l),
            None => s.line(&format!("printf 'warning: %s has a newline and is not passed\\n' {}", sh_quote(&k))),
        }
    }

    if fresh {
        match &c.source {
            Source::Image { .. } | Source::Dockerfile { .. } => {
                let image = match &c.source {
                    Source::Image { image } => {
                        s.step(&format!("Image {image}"));
                        s.line(&format!("if \"$DOCKER\" image inspect {} >/dev/null 2>&1; then echo 'present'; else", sh_quote(image)));
                        let argv = vec![i.docker.to_string(), "pull".into(), image.clone()];
                        s.run(&q(&argv), &argv, T_BUILD, "could not pull the image");
                        s.line("fi");
                        image.clone()
                    }
                    Source::Dockerfile { dockerfile, context, args, target, cache_from, options } => {
                        s.step("Building the image");
                        let shown_args = match &i.shown.source {
                            Source::Dockerfile { args, .. } => args.clone(),
                            _ => BTreeMap::new(),
                        };
                        let mut argv = vec![i.docker.to_string(), "build".into(), "-f".into(), dockerfile.clone(), "-t".into(), i.image_tag.clone()];
                        let mut prefix = String::new();
                        let mut shown_argv = argv.clone();
                        for (k, v) in args {
                            if shown_args.get(k) == Some(v) {
                                argv.extend(["--build-arg".into(), format!("{k}={v}")]);
                                shown_argv.extend(["--build-arg".into(), format!("{k}={v}")]);
                            } else if super::config::valid_env_name(k) {
                                // From the host environment: through the environment only.
                                env.push((format!("WB_B_{k}"), Some(v.clone())));
                                let _ = write!(prefix, "{k}=\"$WB_B_{k}\" ");
                                argv.extend(["--build-arg".into(), k.clone()]);
                                shown_argv.extend(["--build-arg".into(), format!("{k}={}", shown_args.get(k).cloned().unwrap_or_default())]);
                                secrets.push(v.clone());
                            }
                        }
                        if let Some(t) = target {
                            argv.extend(["--target".into(), t.clone()]);
                            shown_argv.extend(["--target".into(), t.clone()]);
                        }
                        for cf in cache_from {
                            argv.extend(["--cache-from".into(), cf.clone()]);
                            shown_argv.extend(["--cache-from".into(), cf.clone()]);
                        }
                        argv.extend(options.iter().cloned());
                        shown_argv.extend(options.iter().cloned());
                        for (k, v) in [("workbench.project", i.project_id), ("devcontainer.local_folder", root.as_str())] {
                            argv.extend(["--label".into(), format!("{k}={v}")]);
                        }
                        argv.push(context.clone());
                        shown_argv.push(context.clone());
                        s.show(&q(&shown_argv));
                        s.line(&format!("{prefix}run {T_BUILD} {} || fail 'the image build failed'", q(&argv)));
                        i.image_tag.clone()
                    }
                    _ => unreachable!(),
                };
                s.line(&format!("IMG={}", sh_quote(&image)));

                // updateRemoteUserUID: match the container user's UID to ours (Linux).
                if c.update_remote_user_uid && i.host_uid != 0 {
                    let uid_df = i.work.join("updateUID.Dockerfile");
                    std::fs::write(&uid_df, UID_DOCKERFILE)?;
                    let empty = i.work.join("empty-context");
                    std::fs::create_dir_all(&empty)?;
                    let u = user.clone().unwrap_or_default();
                    s.line(&format!("U={}", sh_quote(&u)));
                    s.line("if [ -z \"$U\" ]; then U=$(meta_user image inspect \"$IMG\"); fi");
                    s.line("if [ -z \"$U\" ]; then U=$(\"$DOCKER\" image inspect --format '{{.Config.User}}' \"$IMG\" 2>/dev/null); fi");
                    s.line("IMAGE_USER=$(\"$DOCKER\" image inspect --format '{{.Config.User}}' \"$IMG\" 2>/dev/null); IMAGE_USER=${IMAGE_USER:-root}");
                    s.line("case \"${U%%:*}\" in ''|root|0|[0-9]*) ;; *)");
                    s.step("Matching the container user's UID to yours");
                    let tag = format!("{}-uid", i.image_tag.split(':').next().unwrap_or(&i.image_tag));
                    s.line(&format!(
                        "  show \"docker build (updateRemoteUserUID: $U → {uid}:{gid})\"\n  run {T_BUILD} \"$DOCKER\" build -q -f {df} -t {tag} --build-arg BASE_IMAGE=\"$IMG\" --build-arg REMOTE_USER=\"${{U%%:*}}\" --build-arg NEW_UID={uid} --build-arg NEW_GID={gid} --build-arg IMAGE_USER=\"$IMAGE_USER\" {ctx} || fail 'could not update the user UID'\n  IMG={tag};;",
                        uid = i.host_uid,
                        gid = i.host_gid,
                        df = sh_quote(&uid_df.display().to_string()),
                        ctx = sh_quote(&empty.display().to_string()),
                        tag = sh_quote(&tag),
                    ));
                    s.line("esac");
                }

                // docker run
                s.step("Creating the container");
                let mut argv: Vec<String> = vec![i.docker.to_string(), "run".into(), "-d".into()];
                if own_name.is_none() {
                    argv.extend(["--name".into(), i.container_name.clone()]);
                } else if let Some(n) = &own_name {
                    argv.extend(["--name".into(), n.clone()]);
                }
                for (k, v) in [
                    ("devcontainer.local_folder", root.as_str()),
                    ("devcontainer.config_file", config_file.as_str()),
                    ("workbench.project", i.project_id),
                    ("workbench.config-hash", i.hash),
                ] {
                    argv.extend(["--label".into(), format!("{k}={v}")]);
                }
                // The users go into VS Code's metadata label; without them the image's
                // own label (mcr.microsoft.com/devcontainers images name `vscode`) stays.
                if let Some(m) = metadata_label(c) {
                    argv.extend(["--label".into(), format!("devcontainer.metadata={m}")]);
                }
                if let Some(m) = &c.workspace_mount {
                    argv.extend(["--mount".into(), m.spec.clone()]);
                }
                for m in &c.mounts {
                    argv.extend(["--mount".into(), m.spec.clone()]);
                }
                for (port, host) in &i.publish {
                    let spec = if *host == 0 { format!("127.0.0.1::{port}") } else { format!("127.0.0.1:{host}:{port}") };
                    argv.extend(["-p".into(), spec]);
                }
                if !env_text.is_empty() {
                    crate::util::fs::write_atomic(&env_file, env_text.as_bytes(), 0o600)?;
                    temp.push(env_file.clone());
                    argv.extend(["--env-file".into(), env_file.display().to_string()]);
                }
                if c.init {
                    argv.push("--init".into());
                }
                if c.privileged {
                    argv.push("--privileged".into());
                }
                for cap in &c.cap_add {
                    argv.extend(["--cap-add".into(), cap.clone()]);
                }
                for o in &c.security_opt {
                    argv.extend(["--security-opt".into(), o.clone()]);
                }
                if let Some(u) = &c.container_user {
                    argv.extend(["-u".into(), u.clone()]);
                }
                argv.extend(run_args.iter().cloned());
                if c.override_command {
                    argv.extend(["--entrypoint".into(), "/bin/sh".into()]);
                }
                let shown = format!("{} \"$IMG\"{}", q(&argv), if c.override_command { " -c <keep-alive>" } else { "" });
                s.show(&shown);
                let tail = if c.override_command { format!(" -c {}", sh_quote_always(KEEP_ALIVE)) } else { String::new() };
                s.line(&format!("CID=$(run {T_RUN} {} \"$IMG\"{tail}) || {{ rm -f {ef}; fail 'could not create the container'; }}", q(&argv), ef = sh_quote(&env_file.display().to_string())));
                s.line(&format!("rm -f {}", sh_quote(&env_file.display().to_string())));
                s.line("CID=${CID##*$'\\n'}; printf 'container %s\\n' \"${CID:0:12}\"");
            }
            Source::Compose { files, service, run_services } => {
                s.step("docker compose up");
                let override_file = i.work.join("compose.override.yml");
                let mut svc = serde_json::Map::new();
                let mut labels = serde_json::Map::new();
                for (k, v) in [
                    ("devcontainer.local_folder", root.as_str()),
                    ("devcontainer.config_file", config_file.as_str()),
                    ("workbench.project", i.project_id),
                    ("workbench.config-hash", i.hash),
                ] {
                    labels.insert(k.into(), json!(v));
                }
                if let Some(m) = metadata_label(c) {
                    labels.insert("devcontainer.metadata".into(), json!(m));
                }
                svc.insert("labels".into(), serde_json::Value::Object(labels));
                if !c.container_env.is_empty() {
                    svc.insert("environment".into(), json!(c.container_env));
                }
                if c.override_command {
                    svc.insert("entrypoint".into(), json!(["/bin/sh", "-c", KEEP_ALIVE.replace('$', "$$"), "-"]));
                    svc.insert("command".into(), json!([]));
                }
                if c.init {
                    svc.insert("init".into(), json!(true));
                }
                if c.privileged {
                    svc.insert("privileged".into(), json!(true));
                }
                if !c.cap_add.is_empty() {
                    svc.insert("cap_add".into(), json!(c.cap_add));
                }
                if !c.security_opt.is_empty() {
                    svc.insert("security_opt".into(), json!(c.security_opt));
                }
                if let Some(u) = &c.container_user {
                    svc.insert("user".into(), json!(u));
                }
                if !c.mounts.is_empty() {
                    let vols: Vec<serde_json::Value> = c
                        .mounts
                        .iter()
                        .map(|m| {
                            let mut o = json!({ "type": m.kind, "target": m.target });
                            if !m.source.is_empty() {
                                o["source"] = json!(m.source);
                            }
                            if m.readonly {
                                o["read_only"] = json!(true);
                            }
                            o
                        })
                        .collect();
                    svc.insert("volumes".into(), json!(vols));
                }
                let doc = json!({ "services": { service.clone(): serde_json::Value::Object(svc) } });
                let yaml = serde_norway::to_string(&doc)?;
                crate::util::fs::write_atomic(&override_file, yaml.as_bytes(), 0o600)?;
                temp.push(override_file.clone());
                let mut base: Vec<String> = vec![i.docker.to_string(), "compose".into(), "-p".into(), i.compose_project.clone()];
                for f in files {
                    base.extend(["-f".into(), f.clone()]);
                }
                base.extend(["-f".into(), override_file.display().to_string()]);
                let mut up = base.clone();
                up.extend(["up".into(), "-d".into(), "--build".into()]);
                if !run_services.is_empty() {
                    up.push(service.clone());
                    up.extend(run_services.iter().filter(|r| *r != service).cloned());
                }
                s.run(&q(&up), &up, T_BUILD, "docker compose up failed");
                let mut ps = base.clone();
                ps.extend(["ps".into(), "-q".into(), service.clone()]);
                s.line(&format!("CID=$(run {T_SHORT} {}) || fail 'cannot find the service container'", q(&ps)));
                s.line(&format!("rm -f {}", sh_quote(&override_file.display().to_string())));
                s.line("[ -n \"$CID\" ] || fail 'the service container did not start'");
                // `up` on an existing stack keeps an unchanged container: not fresh then.
                if let (Some(e), false) = (i.existing, i.rebuild) {
                    s.line(&format!("if [ \"$CID\" = {} ]; then FRESH=0; STARTED={}; fi", sh_quote(&e.id), if e.running { 0 } else { 1 }));
                }
            }
            Source::None => anyhow::bail!("the config names no image, Dockerfile or compose file"),
        }
    }

    // Lifecycle hooks: the create hooks once per container (FRESH, or a container of
    // ours whose marker is missing), postStart when it started, postAttach always.
    let shown = i.shown;
    let create_hooks = [
        ("onCreateCommand", &c.on_create_command, &shown.on_create_command),
        ("updateContentCommand", &c.update_content_command, &shown.update_content_command),
        ("postCreateCommand", &c.post_create_command, &shown.post_create_command),
    ];
    if i.check_marker && !fresh {
        s.line(&format!("\"$DOCKER\" exec -u root \"$CID\" test -f {MARKER} >/dev/null 2>&1 || FRESH=1"));
    }
    s.line("if [ \"$FRESH\" = 1 ]; then");
    s.line(":");
    for (key, l, sl) in create_hooks {
        if let Some(l) = l {
            hook_lines(&mut s, key, l, sl.as_ref());
        }
    }
    s.line(&format!(
        "\"$DOCKER\" exec -u root \"$CID\" /bin/sh -c 'mkdir -p {dir} && date > {m}' >/dev/null 2>&1 || true",
        dir = Path::new(MARKER).parent().map(|p| p.display().to_string()).unwrap_or_default(),
        m = MARKER
    ));
    s.line("fi");
    if let Some(l) = &c.post_start_command {
        s.line("if [ \"$STARTED\" = 1 ]; then");
        hook_lines(&mut s, "postStartCommand", l, shown.post_start_command.as_ref());
        s.line("fi");
    }
    if let Some(l) = &c.post_attach_command {
        hook_lines(&mut s, "postAttachCommand", l, shown.post_attach_command.as_ref());
    }
    s.line("printf '\\n%s✔ Dev container is ready (%s)%s\\n' \"$C_OK\" \"${CID:0:12}\" \"$C_RST\"");
    Ok(UpScript { script: s.s, env, result_file: None, temp_files: temp, secrets })
}

/// `devcontainer up`'s result: the last JSON line of its stdout.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliResult {
    pub outcome: String,
    pub container_id: Option<String>,
    pub remote_user: Option<String>,
    pub remote_workspace_folder: Option<String>,
    pub compose_project: Option<String>,
    pub message: Option<String>,
}

pub fn parse_cli_result(stdout: &str) -> Option<CliResult> {
    let line = stdout.lines().rev().find(|l| l.trim_start().starts_with('{'))?;
    let v: serde_json::Value = serde_json::from_str(line.trim()).ok()?;
    let s = |k: &str| v.get(k).and_then(|x| x.as_str()).map(str::to_string);
    Some(CliResult {
        outcome: s("outcome").unwrap_or_default(),
        container_id: s("containerId"),
        remote_user: s("remoteUser"),
        remote_workspace_folder: s("remoteWorkspaceFolder"),
        compose_project: s("composeProjectName"),
        message: s("message").or_else(|| s("description")),
    })
}

/// The compose project name the devcontainer CLI would pick: `<folder>_devcontainer`,
/// lowercased, with characters compose refuses removed.
pub fn compose_project_name(root: &Path) -> String {
    let base = root.file_name().map(|n| n.to_string_lossy().to_lowercase()).unwrap_or_else(|| "project".into());
    let clean: String = base.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-').collect();
    format!("{}_devcontainer", if clean.is_empty() { "project" } else { &clean })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_args_are_filtered_and_env_leaves_argv() {
        let args: Vec<String> = ["--rm", "-it", "--cap-add=SYS_PTRACE", "-e", "TOKEN=abc", "--env=B=2", "-e", "KEEP", "--name", "mine", "--cidfile", "/tmp/x", "--label", "workbench.test=1"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        let (out, env, name) = filter_run_args(&args);
        assert_eq!(out, vec!["--cap-add=SYS_PTRACE", "-e", "KEEP", "--label", "workbench.test=1"]);
        assert_eq!(env, vec![("TOKEN".to_string(), "abc".to_string()), ("B".to_string(), "2".to_string())]);
        assert_eq!(name.as_deref(), Some("mine"));
    }

    #[test]
    fn cli_results() {
        let out = "some log\n{\"outcome\":\"success\",\"containerId\":\"abc\",\"remoteUser\":\"vscode\",\"remoteWorkspaceFolder\":\"/workspaces/app\"}\n";
        let r = parse_cli_result(out).unwrap();
        assert_eq!(r.outcome, "success");
        assert_eq!(r.container_id.as_deref(), Some("abc"));
        assert_eq!(r.remote_user.as_deref(), Some("vscode"));
        assert!(parse_cli_result("no json").is_none());
        assert_eq!(compose_project_name(Path::new("/home/u/My App")), "myapp_devcontainer");
    }
}
