//! Task runner fixtures: Makefile, justfile, Taskfile, Procfile.

use super::super::tasks::{just_recipes, make_targets, needs_args, taskfile_tasks};
use super::{detect_checked, has_run, names, run, tree};
use crate::config::project::RunKind;

const MAKEFILE: &str = "# Project tasks
BIN := bin/app
GOFLAGS ?= -trimpath
VERSION = $(shell git describe)

.PHONY: all build test lint fmt run dev clean \\
        docker-build db.migrate _internal

all: build

build: ## Build the binary
\tgo build -o $(BIN) ./cmd/app

test:
\tgo test ./...

lint fmt:
\tgolangci-lint run

run: build
\t./$(BIN) --port 8088

dev:
\tair

clean:
\trm -rf bin/

docker-build:
\tdocker build -t app .

db.migrate:
\tmigrate -path db -database $$DATABASE_URL up

deploy: build
\trsync -av bin/ prod:/opt/app/
\tssh prod systemctl restart app

publish:
\tdocker push registry.example.com/app:latest

_internal:
\techo private

%.o: %.c
\t$(CC) -c $<

$(BIN): main.go
\tgo build -o $@

bin/tool: tool.go
\tgo build -o $@

main.o: main.c
\tcc -c main.c

install:
\tcp $(BIN) /usr/local/bin
";

#[test]
fn makefile_targets() {
    let t = make_targets(MAKEFILE);
    let got: Vec<&str> = t.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(
        got,
        vec!["all", "build", "test", "lint", "fmt", "run", "dev", "clean", "docker-build", "db.migrate", "deploy", "publish", "install"],
        "phony + conventional names; no patterns, variables, paths, files or private targets"
    );
    let run_body = &t.iter().find(|e| e.name == "run").unwrap().body;
    assert!(run_body.contains("--port 8088"), "{run_body}");
    assert!(make_targets("# CMAKE generated file: DO NOT EDIT!\nall: cmake_check_build_system\n").is_empty());
    assert!(make_targets("# Makefile.in generated by automake 1.16.5 from Makefile.am.\nall: x\n").is_empty());
}

#[test]
fn makefile_runs() {
    let d = tree(&[("Makefile", MAKEFILE), ("docs/Makefile", ".PHONY: help html\nhelp:\n\t@sphinx-build -M help . _build\nhtml:\n\tsphinx-build -b html . _build\n")]);
    let pf = detect_checked(d.path());
    let r = run(&pf, "make run");
    assert_eq!((r.kind, r.command.as_str(), r.port), (RunKind::Server, "make run", Some(8088)));
    assert_eq!(r.source.as_deref(), Some("detected:Makefile#run"));
    assert_eq!(run(&pf, "make dev").kind, RunKind::Server);
    assert_eq!(run(&pf, "make test").kind, RunKind::Test);
    assert_eq!(run(&pf, "make build").kind, RunKind::Build);
    assert_eq!(run(&pf, "make all").kind, RunKind::Build);
    assert_eq!(run(&pf, "make lint").kind, RunKind::Task);
    assert_eq!(run(&pf, "make clean").group.as_deref(), Some("tasks"));
    // A recipe that reaches another machine or publishes is a deploy, whatever its name.
    assert_eq!(run(&pf, "make deploy").group.as_deref(), Some("deploy"));
    assert_eq!(run(&pf, "make publish").group.as_deref(), Some("deploy"));
    assert!(crate::apps::runs::needs_confirmation(run(&pf, "make publish")));
    assert_eq!(run(&pf, "make html (docs)").cwd, "docs");
}

const JUSTFILE: &str = r#"set dotenv-load
set shell := ["bash", "-cu"]

alias b := build
export RUST_LOG := "info"
version := `git describe --tags`

# Show the recipes
default:
    @just --list

# Build everything
build *args:
    cargo build {{args}}

[group('dev')]
serve port="8000":
    python -m http.server {{port}}

test filter="": build
    cargo test {{filter}}

deploy env:
    ./scripts/deploy.sh {{env}}

[private]
helper:
    echo hidden

_hidden:
    echo hidden

[windows]
win-only:
    echo windows

[linux]
linux-only:
    echo linux

files +paths:
    ls {{paths}}

ship:
    rsync -av dist/ web:/var/www/
"#;

#[test]
fn justfile_recipes() {
    let r = just_recipes(JUSTFILE);
    let got: Vec<&str> = r.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(got, vec!["default", "build", "serve", "test", "linux-only", "ship"]);
    assert!(needs_args("env") && needs_args("+paths") && needs_args("$name"));
    assert!(!needs_args("*args") && !needs_args("port=\"8000\"") && !needs_args("filter=\"a b\"") && !needs_args(""));
    let d = tree(&[("justfile", JUSTFILE)]);
    let pf = detect_checked(d.path());
    let s = run(&pf, "just serve");
    assert_eq!((s.kind, s.command.as_str()), (RunKind::Server, "just serve"));
    assert_eq!(run(&pf, "just test").kind, RunKind::Test);
    assert_eq!(run(&pf, "just ship").group.as_deref(), Some("deploy"));
    assert!(!has_run(&pf, "just deploy") && !has_run(&pf, "just helper"), "{:?}", names(&pf));
}

const TASKFILE: &str = r#"version: '3'

vars:
  APP: widget

tasks:
  default:
    cmds:
      - task --list
  build:
    desc: Build the app
    cmds:
      - go build -o bin/{{.APP}} .
  dev:
    deps: [build]
    cmds:
      - ./bin/{{.APP}} -addr :4040
  test: go test ./...
  lint: [golangci-lint run, echo done]
  docker:push:
    cmds:
      - docker push ghcr.io/acme/widget
  gen:internal:
    internal: true
    cmds: [go generate ./...]
  mac-only:
    platforms: [darwin]
    cmds: [brew bundle]
  release:
    requires:
      vars: [VERSION]
    cmds: [goreleaser release]
"#;

#[test]
fn taskfile_tasks_and_runs() {
    let t = taskfile_tasks(TASKFILE);
    let got: Vec<&str> = t.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(got, vec!["default", "build", "dev", "test", "lint", "docker:push"]);
    let d = tree(&[("Taskfile.yml", TASKFILE)]);
    let pf = detect_checked(d.path());
    let dev = run(&pf, "task dev");
    assert_eq!((dev.kind, dev.port), (RunKind::Server, Some(4040)));
    assert!(dev.command.ends_with("task dev"), "{}", dev.command);
    assert_eq!(run(&pf, "task test").kind, RunKind::Test);
    assert_eq!(run(&pf, "task docker:push").group.as_deref(), Some("deploy"));
}

#[test]
fn procfiles() {
    let d = tree(&[
        ("Procfile", "web: gunicorn app:app --bind 0.0.0.0:$PORT\nworker: celery -A app worker\nrelease: python manage.py migrate\n# comment\n"),
        ("Procfile.dev", "web: bin/rails server -p ${PORT:-3000}\ncss: bin/rails tailwindcss:watch\n"),
    ]);
    let pf = detect_checked(d.path());
    let web = run(&pf, "Procfile: web");
    assert_eq!((web.kind, web.port, web.command.as_str()), (RunKind::Server, Some(5000), "gunicorn app:app --bind 0.0.0.0:$PORT"));
    assert_eq!(web.env.get("PORT").map(String::as_str), Some("5000"));
    assert_eq!(run(&pf, "Procfile: worker").kind, RunKind::Task);
    assert!(!has_run(&pf, "Procfile: release"), "the release phase runs on deploy");
    let dev = run(&pf, "Procfile.dev: web");
    assert_eq!((dev.port, dev.env.get("PORT").map(String::as_str)), (Some(3000), Some("3000")));
    assert_eq!(run(&pf, "Procfile.dev: css").port, None);

    // Rails 7: `web: bin/rails server` repeats `rails server`; a web process that
    // ignores $PORT has no port to claim; Python's http.server listens on 8000.
    let d = tree(&[
        ("Gemfile", "gem \"rails\"\n"),
        ("config/application.rb", "module App; end\n"),
        ("bin/rails", ""),
        ("Procfile.dev", "web: bin/rails server\njs: yarn build --watch\n"),
        ("worker/Procfile", "web: ./bin/serve-forever\n"),
        ("static/Procfile", "web: python -m http.server\n"),
    ]);
    let pf = detect_checked(d.path());
    assert!(!has_run(&pf, "Procfile.dev: web"), "{:?}", names(&pf));
    assert_eq!(run(&pf, "rails server").port, Some(3000));
    assert_eq!(run(&pf, "Procfile.dev: js").kind, RunKind::Task);
    let w = run(&pf, "Procfile: web (worker)");
    assert_eq!((w.kind, w.port, w.env.is_empty()), (RunKind::Server, None, true));
    let s = run(&pf, "Procfile: web (static)");
    assert_eq!((s.kind, s.port, s.preview.as_deref()), (RunKind::Server, Some(8000), Some("http://localhost:8000/")));
}

/// Rails 7 with `bin/dev`: `Procfile.dev`'s `web: bin/rails server -p 3000` is the
/// `rails server` run again (same program, same port), not a third server on :3000.
#[test]
fn rails_procfile_dev_web_is_not_a_third_server() {
    let d = tree(&[
        ("Gemfile", "gem \"rails\"\n"),
        ("config/application.rb", "module App; end\n"),
        ("bin/rails", ""),
        ("bin/dev", "#!/usr/bin/env sh\nexec foreman start -f Procfile.dev\n"),
        ("Procfile.dev", "web: bin/rails server -p 3000\ncss: bin/rails tailwindcss:watch\n"),
        ("api/Procfile", "web: bundle exec puma -p 9000\n"),
    ]);
    let pf = detect_checked(d.path());
    let servers: Vec<&str> = pf.runs.iter().filter(|r| r.port == Some(3000)).map(|r| r.name.as_str()).collect();
    assert_eq!(servers, vec!["bin/dev", "rails server"], "{:?}", names(&pf));
    assert!(has_run(&pf, "Procfile.dev: css"), "{:?}", names(&pf));
    assert_eq!(run(&pf, "Procfile: web (api)").port, Some(9000), "another directory, another server");
}

/// `python -m http.server [port]`: a server with a port, a ready line and a preview.
#[test]
fn python_http_server_has_a_port_and_a_ready_line() {
    use super::super::port_in;
    assert_eq!(port_in("python3 -m http.server 8123 --bind 127.0.0.1"), Some(8123));
    assert_eq!(port_in("python -m http.server"), Some(8000));
    assert_eq!(port_in("python3 -m http.server -b 0.0.0.0 -d site 9001"), Some(9001));
    assert_eq!(port_in("python3 -m http.server --directory site"), Some(8000));
    assert_eq!(port_in("python3 -m http.server $PORT"), None, "the $PORT convention decides");
    assert_eq!(port_in("python3 -m http.server --bind 0.0.0.0:7000"), Some(7000));
    let d = tree(&[
        ("Procfile", "web: python3 -m http.server 8123 --bind 127.0.0.1\n"),
        ("Makefile", ".PHONY: serve docs\nserve:\n\tcd site && python3 -m http.server 8765\ndocs:\n\tpython3 -m http.server\n"),
    ]);
    let pf = detect_checked(d.path());
    let web = run(&pf, "Procfile: web");
    assert_eq!((web.kind, web.port, web.preview.as_deref()), (RunKind::Server, Some(8123), Some("http://localhost:8123/")));
    let ready = regex::Regex::new(web.ready.as_ref().and_then(|r| r.log.as_deref()).unwrap()).unwrap();
    let line = "Serving HTTP on 127.0.0.1 port 8123 (http://127.0.0.1:8123/) ...";
    assert_eq!(ready.captures(line).unwrap().get(1).map(|m| m.as_str()), Some("http://127.0.0.1:8123/"));
    let serve = run(&pf, "make serve");
    assert_eq!((serve.kind, serve.port, serve.ready.is_some()), (RunKind::Server, Some(8765), true));
    assert_eq!((run(&pf, "make docs").port, run(&pf, "make docs").ready.is_none()), (None, true), "a task is not a server");
}

/// A dependency-only recipe that only names another offered one (`default: up`)
/// is not offered twice; an aggregate of several is kept.
#[test]
fn just_aliases_are_not_offered_twice() {
    let src = "default: up\nup:\n    docker compose up -d\nci: lint test\nlint:\n    ruff check .\ntest:\n    pytest\nhidden: _setup\n_setup:\n    ./setup.sh\n";
    let got: Vec<String> = just_recipes(src).into_iter().map(|e| e.name).collect();
    assert_eq!(got, vec!["up", "ci", "lint", "test", "hidden"]);
}

#[test]
fn same_name_in_one_directory_is_qualified_by_tool() {
    // A Python console script `serve` next to an npm script `serve`.
    let d = tree(&[
        ("package.json", r#"{"scripts":{"serve":"vite preview"}}"#),
        ("pyproject.toml", "[project]\nname = \"x\"\n[project.scripts]\nserve = \"x.cli:serve\"\n"),
    ]);
    let pf = detect_checked(d.path());
    assert_eq!(run(&pf, "serve").command, "npm run serve");
    assert_eq!(run(&pf, "serve · pyproject").command, "serve");
}
